export { default as Gallery } from "./Gallery";
export { default as Reviews } from "./Reviews";
export { default as Contacts } from "./Contacts";
export { default as Delivery } from "./Delivery";
export { default as ProductView } from "./ProductView";
export { default as ClientsView } from "./ClientsView";
export { default as ServiceCenter } from "./ServiceCenter";
export { default as CertificatesView } from "./CertificatesView";
export { default as PlacingAndMontage } from "./PlacingAndMontage";
